from shapely.geometry import Point
import matplotlib.pyplot as plt
import pandas as pd
import nhood_objects as nho
from inspect import getmembers
import string
import sys
from lookup_name import lookup_name as lun
from check_quad import check_quad as chq




def check_nhood(pnt):
    x=0
    ff = 0
    point = pnt
#    print(point)
    neighborhoods = [
nho.Abell.contains(point),
nho.Allendale.contains(point),
nho.Arcadia.contains(point),
nho.Arlington.contains(point),
nho.Armistead_Gardens.contains(point),
nho.Ashburton.contains(point),
nho.Baltimore_Highlands.contains(point),
nho.Barclay.contains(point),
nho.Barre_Circle.contains(point),
nho.Bayview.contains(point),
nho.Beechfield.contains(point),
nho.Belair_Edison.contains(point),
nho.Belair_Parkside.contains(point),
nho.Bellona_Gittings.contains(point),
nho.Belvedere.contains(point),
nho.Berea.contains(point),
nho.Better_Waverly.contains(point),
nho.Beverly_Hills.contains(point),
nho.Biddle_Street.contains(point),
nho.Blythewood.contains(point),
nho.Bolton_Hill.contains(point),
nho.Boyd_Booth.contains(point),
nho.Brewers_Hill.contains(point),
nho.Bridgeview_Greenlawn.contains(point),
nho.Broadway_East.contains(point),
nho.Broening_Manor.contains(point),
nho.Brooklyn.contains(point),
nho.Burleith_Leighton.contains(point),
nho.ButcherS_Hill.contains(point),
nho.Callaway_Garrison.contains(point),
nho.Cameron_Village.contains(point),
nho.Canton.contains(point),
nho.Canton_Industrial_Area.contains(point),
nho.Care.contains(point),
nho.Carroll_Park.contains(point),
nho.Carroll_South_Hilton.contains(point),
nho.Carroll___Camden_Industrial_Area.contains(point),
nho.Carrollton_Ridge.contains(point),
nho.Cedarcroft.contains(point),
nho.Cedmont.contains(point),
nho.Cedonia.contains(point),
nho.Central_Forest_Park.contains(point),
nho.Central_Park_Heights.contains(point),
nho.Charles_North.contains(point),
nho.Charles_Village.contains(point),
nho.Cherry_Hill.contains(point),
nho.Cheswolde.contains(point),
nho.Chinquapin_Park.contains(point),
nho.Clifton_Park.contains(point),
nho.Coldspring.contains(point),
nho.Coldstream_Homestead_Montebello.contains(point),
nho.Concerned_Citizens_Of_Forest_Park.contains(point),
nho.Coppin_HeightsAsh_Co_East.contains(point),
nho.Cross_Country.contains(point),
nho.Cross_Keys.contains(point),
nho.Curtis_Bay.contains(point),
nho.Curtis_Bay_Industrial_Area.contains(point),
nho.Cylburn.contains(point),
nho.Darley_Park.contains(point),
nho.Dickeyville.contains(point),
nho.Dolfield.contains(point),
nho.Dorchester.contains(point),
nho.Downtown.contains(point),
nho.Downtown_West.contains(point),
nho.Druid_Heights.contains(point),
nho.Druid_Hill_Park.contains(point),
nho.Dunbar_Broadway.contains(point),
nho.Dundalk_Marine_Terminal.contains(point),
nho.East_Arlington.contains(point),
nho.East_Baltimore_Midway.contains(point),
nho.Easterwood.contains(point),
nho.Eastwood.contains(point),
nho.Edgewood.contains(point),
nho.Edmondson_Village.contains(point),
nho.Ednor_Gardens_Lakeside.contains(point),
nho.Ellwood_Park_Monument.contains(point),
nho.Evergreen.contains(point),
nho.Evergreen_Lawn.contains(point),
nho.Evesham_Park.contains(point),
nho.Fairfield_Area.contains(point),
nho.Fairmont.contains(point),
nho.Fallstaff.contains(point),
nho.Federal_Hill.contains(point),
nho.Fells_Point.contains(point),
nho.Forest_Park.contains(point),
nho.Forest_Park_Golf_Course.contains(point),
nho.Four_By_Four.contains(point),
nho.Frankford.contains(point),
nho.Franklin_Square.contains(point),
nho.Franklintown.contains(point),
nho.Franklintown_Road.contains(point),
nho.Garwyn_Oaks.contains(point),
nho.Gay_Street.contains(point),
nho.Glen.contains(point),
nho.Glen_Oaks.contains(point),
nho.Glenham_Belhar.contains(point),
nho.Graceland_Park.contains(point),
nho.Greektown.contains(point),
nho.Greenmount_Cemetery.contains(point),
nho.Greenmount_West.contains(point),
nho.Greenspring.contains(point),
nho.Grove_Park.contains(point),
nho.Guilford.contains(point),
nho.Gwynns_Falls.contains(point),
nho.Gwynns_Falls_Leakin_Park.contains(point),
nho.Hamilton_Hills.contains(point),
nho.Hampden.contains(point),
nho.Hanlon_Longwood.contains(point),
nho.Harlem_Park.contains(point),
nho.Harwood.contains(point),
nho.Hawkins_Point.contains(point),
nho.Heritage_Crossing.contains(point),
nho.Herring_Run_Park.contains(point),
nho.Highlandtown.contains(point),
nho.Hillen.contains(point),
nho.Hoes_Heights.contains(point),
nho.Holabird_Industrial_Park.contains(point),
nho.Hollins_Market.contains(point),
nho.Homeland.contains(point),
nho.Hopkins_Bayview.contains(point),
nho.Howard_Park.contains(point),
nho.Hunting_Ridge.contains(point),
nho.Idlewood.contains(point),
nho.Inner_Harbor.contains(point),
nho.Irvington.contains(point),
nho.Johns_Hopkins_Homewood.contains(point),
nho.Johnston_Square.contains(point),
nho.Jones_Falls_Area.contains(point),
nho.Jonestown.contains(point),
nho.Kenilworth_Park.contains(point),
nho.Kernewood.contains(point),
nho.Keswick.contains(point),
nho.Kresson.contains(point),
nho.Lake_Evesham.contains(point),
nho.Lake_Walker.contains(point),
nho.Lakeland.contains(point),
nho.Langston_Hughes.contains(point),
nho.Lauraville.contains(point),
nho.Levindale.contains(point),
nho.Liberty_Square.contains(point),
nho.Little_Italy.contains(point),
nho.Loch_Raven.contains(point),
nho.Locust_Point.contains(point),
nho.Locust_Point_Industrial_Area.contains(point),
nho.Lower_Edmondson_Village.contains(point),
nho.Lower_Herring_Run_Park.contains(point),
nho.Loyola_Notre_Dame.contains(point),
nho.Lucille_Park.contains(point),
nho.Madison_Eastend.contains(point),
nho.Madison_Park.contains(point),
nho.Mayfield.contains(point),
nho.Mcelderry_Park.contains(point),
nho.Medfield.contains(point),
nho.Medford.contains(point),
nho.Mid_Govans.contains(point),
nho.Mid_Town_Belvedere.contains(point),
nho.Middle_Branch_Reedbird_Parks.contains(point),
nho.Middle_East.contains(point),
nho.Midtown_Edmondson.contains(point),
nho.Millhill.contains(point),
nho.Milton_Montford.contains(point),
nho.Mondawmin.contains(point),
nho.Montebello.contains(point),
nho.Moravia_Walther.contains(point),
nho.Morgan_Park.contains(point),
nho.Morgan_State_University.contains(point),
nho.Morrell_Park.contains(point),
nho.Mosher.contains(point),
nho.Mount_Holly.contains(point),
nho.Mount_Vernon.contains(point),
nho.Mount_Washington.contains(point),
nho.Mount_Winans.contains(point),
nho.Mt_Pleasant_Park.contains(point),
nho.New_Northwood.contains(point),
nho.New_Southwest_Mount_Clare.contains(point),
nho.North_Harford_Road.contains(point),
nho.North_Roland_Park_Poplar_Hill.contains(point),
nho.Northwest_Community_Action.contains(point),
nho.ODonnell_Heights.contains(point),
nho.Oakenshawe.contains(point),
nho.Oaklee.contains(point),
nho.Old_Goucher.contains(point),
nho.Oldtown.contains(point),
nho.Oliver.contains(point),
nho.Orangeville.contains(point),
nho.Orangeville_Industrial_Area.contains(point),
nho.Orchard_Ridge.contains(point),
nho.Original_Northwood.contains(point),
nho.Otterbein.contains(point),
nho.Overlea.contains(point),
nho.Panway_Braddish_Avenue.contains(point),
nho.Park_Circle.contains(point),
nho.Parklane.contains(point),
nho.Parkside.contains(point),
nho.Parkview_Woodbrook.contains(point),
nho.Patterson_Park.contains(point),
nho.Patterson_Park_Neighborhood.contains(point),
nho.Patterson_Place.contains(point),
nho.Pen_Lucy.contains(point),
nho.Penn_Fallsway.contains(point),
nho.Penn_North.contains(point),
nho.Penrose_Fayette_Street_Outreach.contains(point),
nho.Perkins_Homes.contains(point),
nho.Perring_Loch.contains(point),
nho.Pimlico_Good_Neighbors.contains(point),
nho.Pleasant_View_Gardens.contains(point),
nho.Poppleton.contains(point),
nho.Port_Covington.contains(point),
nho.Pulaski_Industrial_Area.contains(point),
nho.Purnell.contains(point),
nho.Radnor_Winston.contains(point),
nho.Ramblewood.contains(point),
nho.Reisterstown_Station.contains(point),
nho.Remington.contains(point),
nho.Reservoir_Hill.contains(point),
nho.Richnor_Springs.contains(point),
nho.RidgelyS_Delight.contains(point),
nho.Riverside.contains(point),
nho.Rognel_Heights.contains(point),
nho.Roland_Park.contains(point),
nho.Rosebank.contains(point),
nho.Rosemont.contains(point),
nho.Rosemont_East.contains(point),
nho.Rosemont_Homeowners_Tenants.contains(point),
nho.Sabina_Mattfeldt.contains(point),
nho.Saint_Agnes.contains(point),
nho.Saint_Helena.contains(point),
nho.Saint_Josephs.contains(point),
nho.Saint_Paul.contains(point),
nho.Sandtown_Winchester.contains(point),
nho.Seton_Business_Park.contains(point),
nho.Seton_Hill.contains(point),
nho.Sharp_Leadenhall.contains(point),
nho.Shipley_Hill.contains(point),
nho.South_Baltimore.contains(point),
nho.South_Clifton_Park.contains(point),
nho.Spring_Garden_Industrial_Area.contains(point),
nho.Stadium_Area.contains(point),
nho.Stonewood_Pentwood_Winston.contains(point),
nho.Taylor_Heights.contains(point),
nho.Ten_Hills.contains(point),
nho.The_Orchards.contains(point),
nho.Towanda_Grantley.contains(point),
nho.Tremont.contains(point),
nho.Tuscany_Canterbury.contains(point),
nho.Union_Square.contains(point),
nho.University_Of_Maryland.contains(point),
nho.Uplands.contains(point),
nho.Upper_Fells_Point.contains(point),
nho.Upton.contains(point),
nho.Villages_Of_Homeland.contains(point),
nho.Violetville.contains(point),
nho.Wakefield.contains(point),
nho.Walbrook.contains(point),
nho.Waltherson.contains(point),
nho.Washington_Hill.contains(point),
nho.Washington_Village_Pigtown.contains(point),
nho.Waverly.contains(point),
nho.West_Arlington.contains(point),
nho.West_Forest_Park.contains(point),
nho.West_Hills.contains(point),
nho.Westfield.contains(point),
nho.Westgate.contains(point),
nho.Westport.contains(point),
nho.Wilhelm_Park.contains(point),
nho.Wilson_Park.contains(point),
nho.Winchester.contains(point),
nho.Windsor_Hills.contains(point),
nho.Winston_Govans.contains(point),
nho.Woodberry.contains(point),
nho.Woodbourne_Heights.contains(point),
nho.Woodbourne_Mccabe.contains(point),
nho.Woodmere.contains(point),
nho.Wrenlane.contains(point),
nho.Wyman_Park.contains(point),
nho.Wyndhurst.contains(point),
nho.Yale_Heights.contains(point),
nho.York_Homeland.contains(point),
]
    for name in neighborhoods:
        if name == True: 
            return lun(x), chq(lun(x))
 #           x3,y3 = point.xy
 #           plt.plot(x3, y3, 'k*')
 #           break
        else:
            ff = ff + 1
            if ff == len(neighborhoods):
                x3,y3 = point.xy
                return 'nan','nan'
        x = x + 1

#    plt.show()
