Western = [
'Bridgeview Greenlawn',
'Coppin HeightsAsh Co East',
'Easterwood',
'Evergreen Lawn',
'Franklin Square',
'Harlem Park',
'Midtown Edmondson',
'Mondawmin',
'Mosher',
'Panway Braddish Avenue',
'Parkview Woodbrook',
'Penn North',
'Poppleton',
'Rosemont Homeowners Tenants',
'Sandtown Winchester'
]

Northeastern = [
'Arcadia',
'Armistead Gardens',
'Belair Edison',
'Belair Parkside',
'Better Waverly',
'Beverly Hills',
'Cedmont',
'Cedonia',
'Clifton Park',
'Coldstream Homestead Montebello',
'Darley Park',
'Ednor Gardens Lakeside',
'Four By Four',
'Frankford',
'Glenham Belhar',
'Hamilton Hills',
'Herring Run Park',
'Hillen',
'Idlewood',
'Lauraville',
'Loch Raven',
'Lower Herring Run Park',
'Mayfield',
'Montebello',
'Moravia Walther',
'Morgan Park',
'Morgan State University',
'Mt Pleasant Park',
'New Northwood',
'North Harford Road',
'Orchard Ridge',
'Original Northwood',
'Overlea',
'Parkside',
'Perring Loch',
'Pulaski Industrial Area',
'Ramblewood',
'Rosemont East',
'Stonewood Pentwood Winston',
'Taylor Heights',
'Waltherson',
'Westfield',
'Woodbourne Heights']

Northwestern = [
'Arlington',
'Ashburton',
'Burleith Leighton',
'Callaway Garrison',
'Central Forest Park',
'Central Park Heights',
'Cheswolde',
'Concerned Citizens Of Forest Park',
'Cross Country',
'Dolfield',
'Dorchester',
'East Arlington',
'Fallstaff',
'Forest Park',
'Forest Park Golf Course',
'Garwyn Oaks',
'Glen',
'Grove Park',
'Hanlon Longwood',
'Howard Park',
'Langston Hughes',
'Liberty Square',
'Lucille Park',
'Park Circle',
'Pimlico Good Neighbors',
'Purnell',
'Reisterstown Station',
'Seton Business Park',
'Towanda Grantley',
'West Arlington',
'West Forest Park',
'Windsor Hills',
'Woodmere'
]

Northern = [
'Abell',
'Barclay',
'Bellona Gittings',
'Belvedere',
'Better Waverly',
'Blythewood',
'Cameron Village',
'Cedarcroft',
'Charles North',
'Charles Village',
'Chinquapin Park',
'Coldspring',
'Cross Keys',
'Cylburn',
'Druid Hill Park',
'Evergreen',
'Evesham Park',
'Glen Oaks',
'Greenspring',
'Guilford',
'Hampden',
'Harwood',
'Hoes Heights',
'Homeland',
'Johns Hopkins Homewood',
'Jones Falls Area',
'Kenilworth Park',
'Kernewood',
'Keswick',
'Lake Evesham',
'Lake Walker',
'Levindale',
'Loyola Notre Dame',
'Medfield',
'Mid Govans',
'Mount Washington',
'North Roland Park Poplar Hill',
'Oakenshawe',
'Old Goucher',
'Parklane',
'Pen Lucy',
'Radnor Winston',
'Remington',
'Richnor Springs',
'Roland Park',
'Rosebank',
'Sabina Mattfeldt',
'The Orchards',
'Tuscany Canterbury',
'Villages Of Homeland',
'Waverly',
'Wilson Park',
'Winston Govans',
'Woodberry',
'Woodbourne McCabe',
'Wrenlane',
'Wyman Park',
'Wyndhurst',
'York Homeland']

Central = [
'Bolton Hill',
'Charles North',
'Downtown',
'Downtown West',
'Druid Heights',
'Greenmount West',
'Heritage Crossing',
'Inner Harbor',
'Madison Park',
'Mid Town Belvedere',
'Mount Vernon',
'Poppleton',
'Reservoir Hill',
'Seton Hill',
'University Of Maryland',
'Upton']

Southeastern = [
'Baltimore Highlands',
'Bayview',
'Brewers Hill',
'Broening Manor',
'ButcherS Hill',
'Canton',
'Canton Industrial Area',
'Dunbar Broadway',
'Dundalk Marine Terminal',
'Eastwood',
'Ellwood Park Monument',
'Fells Point',
'Graceland Park',
'Greektown',
'Highlandtown',
'Holabird Industrial Park',
'Hopkins Bayview',
'Jonestown',
'Kresson',
'Little Italy',
'McElderry Park',
'Medford',
'ODonnell Heights',
'Patterson Park',
'Patterson Park Neighborhood',
'Patterson Place',
'Perkins Homes',
'Pleasant View Gardens',
'Pulaski Industrial Area',
'Saint Helena',
'Upper Fells Point',
'Washington Hill']

Eastern = [
'Berea',
'Biddle Street',
'Broadway East',
'Care',
'Darley Park',
'Dunbar Broadway',
'East Baltimore Midway',
'Gay Street',
'Greenmount Cemetery',
'Greenmount West',
'Johnston Square',
'Madison-Eastend',
'Middle East',
'Milton Montford',
'Oldtown',
'Oliver',
'Orangeville',
'Orangeville Industrial Area',
'Penn Fallsway',
'South Clifton Park']

Southwestern = [
'Allendale',
'Beechfield',
'Boyd Booth',
'Carroll South Hilton',
'Carrollton Ridge',
'Dickeyville',
'Edgewood',
'Edmondson Village',
'Fairmont',
'Franklintown',
'Franklintown Road',
'Gwynns Falls',
'Gwynns Falls Leakin Park',
'Hunting Ridge',
'Irvington',
'Lower Edmondson Village',
'Millhill',
'Morrell Park',
'Mount Holly',
'Northwest Community Action',
'Oaklee',
'Penrose Fayette Street Outreach',
'Rognel Heights',
'Rosemont',
'Saint Agnes',
'Saint Josephs',
'Shipley Hill',
'Ten Hills',
'Tremont',
'Uplands',
'Violetville',
'Wakefield',
'Walbrook',
'West Hills',
'Westgate',
'Wilhelm Park',
'Winchester',
'Yale Heights']

Southern = [
'Barre Circle',
'Brooklyn',
'Carroll   Camden Industrial Area',
'Carroll Park',
'Cherry Hill',
'Curtis Bay',
'Curtis Bay Industrial Area',
'Fairfield Area',
'Federal Hill',
'Hawkins Point',
'Hollins Market',
'Lakeland',
'Locust Point',
'Locust Point Industrial Area',
'Middle Branch Reedbird Parks',
'New Southwest Mount Clare',
'Mount Winans',
'Otterbein',
'Port Covington',
'RidgelyS Delight',
'Riverside',
'Saint Paul',
'South Baltimore',
'Sharp Leadenhall',
'Spring Garden Industrial Area',
'Stadium Area',
'Union Square',
'Washington Village Pigtown',
'Westport',
'Carrollton Ridge',
'Downtown West',
'Franklin Square']
  
def check_quad(namer):
    namer = namer.replace("_"," ")
    if namer in Northeastern:
        return 'Northeastern'
    if namer in Western:
        return 'Western'
    if namer in Northwestern:
        return 'Northwestern'
    if namer in Northern:
        return 'Northern'
    if namer in Central:
        return 'Central'
    if namer in Southeastern:
        return 'Southeastern'
    if namer in Eastern:
        return 'Eastern'
    if namer in Southwestern:
        return 'Southwestern'
    if namer in Southern:
        return 'Southern'
    else:   
        return 'No Quadrant'